### PR TITLE
feat: switch to actix-web

### PR DESCRIPTION
**Pull request by infiniwave**
Converts this project from Warp to Actix Web for more speed and versatility.

### CODE REVIEW

**Comment by infiniwave** [comment]
Closes #28, #29, #30, and #31.

**Comment by infiniwave** [comment]
Requires the modification of endpoints on the client and implementation of the CDN.

**Review by Queryzi — DISMISSED** [review]
I approve of this pull request with the new Actix backend in rust.

**Review by Queryzi — APPROVED** [review]
Approved for merge.

**Pull request merged**
